### ISSUE TITLE
1.12 Compatibility

### ISSUE THREAD

**Issue by silverhoneycat** [prism/Prism#102]
Mate. Our server needs you. Be our hero. Update. God bless and kisses from all the girls on our block, yeah.

**Comment by Meronat** [comment]
Is there any specific problem why it's not working? Was there a crash or some kind of error log?

**Comment by silverhoneycat** [comment]
Please note that when it was working, to when we updated to 1.12, no new plugins have been added to cause possible conflict in hopes that they all play nicely. Also, we get the same results whether using the plain jar or the 'all jar'. Console at restart:
19.06 08:16:19 [Server] ERROR Could not load 'plugins/Prism-3.0.0-beta2-45-gfbbeb2b-all.jar' in folder 'plugins'
19.06 08:16:19 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
19.06 08:16:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot-1.12.jar:git-Spigot-0869666-03f1e37]
19.06 08:16:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
19.06 08:16:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:302) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
19.06 08:16:19 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
19.06 08:16:19 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
19.06 08:16:19 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
19.06 08:16:19 [Server] INFO Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
19.06 08:16:19 [Server] INFO ... 6 more
19.06 08:16:19 [Server] INFO Set PluginClassLoader as parallel capable

Let me know if you need more, but it enables another plugin at this point and no prism commands work ingame, just blank air and nothing happens. Thank you for your hard work on this plugin -- It's SO much better than CoreProtect. #Truth

**Comment by viveleroi** [comment]
Prism v3 is for Sponge only. Bukkit-based servers are no longer supported. You might have luck with some community ports, like [GPrism](https://github.com/Gamealition/GPrism).

**Comment by silverhoneycat** [comment]
Shame. They easily could have put this on Spigot with a download fee and made bank. Just saying.
Thank you for the information and the link!
