### ISSUE TITLE
[Question] Status Update?

### ISSUE THREAD

**Issue by yepidoodles** [prism/Prism#103]
Hey,

So is this still being worked on or is it abandoned?

- Alice Sellars
DragonTechMC

**Comment by viveleroi** [comment]
If you mean the bukkit version, it's 100% abandoned although it's been forked and maintained by a few people.

If you mean the sponge version, neither. I don't play Minecraft or run servers anymore so I've little reason to keep working on it and have been focused on other projects. However, I would like to put more time into it, I have some work in progress I could finish sometime, and I've had some help and always accept PRs, so I don't want to say it's abandoned.

**Comment by yepidoodles** [comment]
I meant the Sponge version, I forget that Spigot/ Bukkit still exists sometimes xD

I'm glad to know that it's not completely abandoned, I've been trying to find some devs to work on it, but struggling, I've also been trying to learn Java myself so hopefully I'll find some people to make some PRs or eventually do it myself, if/ when I do, I'm sure I'll be the biggest contributor! (I'm about to open my 3rd modded public server)

I only ask you carry on doing what you're doing here, even if you don't manage to do anything but accept PRs.
