### ISSUE TITLE
Buggy MySQL output

### ISSUE THREAD

**Issue by realKSMC** [prism/Prism#106]
Is there any way to see the player and WorldUuid correctly?
If I currently use `select * from prism_records` it shows me the following:

```
+----+------------+-----------+------------------+-----+----+-----+-----------------+------------------+-------+
| id | Created    | EventName | WorldUuid        | X   | Y  | Z   | Target          | Player           | Cause |
+----+------------+-----------+------------------+-----+----+-----+-----------------+------------------+-------+
|  1 | 1515715974 | break     | OCO▒▒M▒▒.▒3▒
                                                   | -42 | 77 | 226 | minecraft:grass | ▒Yr[▒bC▒▒iX▒▒ۯ         | NULL  |
+----+------------+-----------+------------------+-----+----+-----+-----------------+------------------+-------+
```

**Comment by viveleroi** [comment]
Something must be wrong with the table/data encoding. UUIDs are nothing but alpha-numeric + hyphens so this shouldn't be happening, Prism should use the correct encodings by default. So, I would check which encoding the prism_records table is using.

**Comment by realKSMC** [comment]
How to do this?

**Comment by viveleroi** [comment]
You can use something like `SHOW TABLE STATUS where name like 'prism_records';`.
