### ISSUE TITLE
ServiceLocator use in app overriding Prism's use of ServiceLocator

### ISSUE THREAD

**Issue by dkofoed** [prism/Prism#107]
We have a component that was developed to use the Prism framework (6.3 version) and it contains it's own shell, bootstrapper, etc.

This component was consumed inside a separate application which happens to make use of the ServiceLocator class for it's own purposes.

What we realized is that the consuming application's use of the ServiceLocator is overriding Prism's use of the ServiceLocator in the "embedded" component. Once the ServiceLocator is accessed at least once in the consuming app, all the lifetime controlled instances in Prism are removed (such as the RegionAdapterMappings, etc) and the embedded component no longer functions correctly.

This is presumably because ServiceLocator is a singleton.

Is there any workaround for this scenario that we may be missing? It seems that the only resolutions are:

1) Remove Prism implementation from the embedded component (probably not practical) OR
2) Remove/change the ServiceLocator implementation in the consuming app (may not be feasible)
3) Other?

**Comment by viveleroi** [comment]
Unfortunately you have the wrong repo, this "Prism" isn't the framework you're referring to.
