### ISSUE TITLE
Track inventory interactions (open, insert, remove)

### ISSUE THREAD

**Issue by viveleroi** [prism/Prism#11]

**Comment by phit** [comment]
any progress on this or a replacement for now?

**Comment by viveleroi** [comment]
I was primarily waiting for Sponge's inventory events to mature though I believe they've made progress lately.

**Comment by inklit** [comment]
This feature would be a huge relief.

**Comment by viveleroi** [comment]
Already in progress.

**Comment by Meegooo** [comment]
Any updates on this? IMO this is the most important feature that is not implemented yet and can't be replaced.

**Comment by viveleroi** [comment]
Work was started and I think @Meronat debated taking this on, but I haven't yet had a chance to do anything further.

**Comment by NEXUS2345** [comment]
Any progress update on this feature? It is really needed for server administration
