### ISSUE TITLE
is this project alive?

### ISSUE THREAD

**Issue by wysohn** [prism/Prism#110]
I'm looking for a good substitue plugin for CoreProtect of Bukkit.

It seems Prism is by far the best, but I can't really tell if anything is under progress

For now, the only downside for using this plugin is it seems to be not tracking the inventory interactions

This is quite a big deal when it comes to recover from grief.

**Comment by viveleroi** [comment]
Prism for bukkit (https://github.com/prism/Prism-Bukkit) had some inventory tracking capabilities.

However, that project is dead since Bukkit is, and this project is *mostly dead*.

**Comment by wysohn** [comment]
How about the Sponge one? is the inventory tracking feature still under progress?

I'm desperately waiting for that :)

Or if this project is simply not continuing, I might have to consider coming up with my own

**Comment by viveleroi** [comment]
It's effectively dead, I guess. I've been hoping that some volunteers come forward and submit PRs to continue it, but I've had no use anymore for it personally and have dedicated time elsewhere.
