### ISSUE TITLE
you come back! :D

### ISSUE THREAD

**Issue by Cavesnakes** [prism/Prism#116]
Prism was great plugin for block log/rollback in MCPC(Bukkit) Era 

I also hope see this plugin long lasting in Sponge Era 
Cheer up! and thanks for your great works

**Comment by viveleroi** [comment]
Thanks, glad you enjoyed it! Mainly thanks to @LXGaming for diving in and trying to get this going again.

**Comment by vedisdragon** [comment]
@viveleroi @nasonfish @bloodmc Hello, I'm actually still running a legacy server on 1.7.10 and I'm in need of a MCPC compatible build. Apologies for bothering you, was unable to receive a response in the IRC and couldn't find working links to the old v2 builds. I know y'all don't support v2 anymore, but access to the old builds would be great. Thank you for your time!

**Comment by viveleroi** [comment]
I don't think we even host the Prism/MCPC builds anymore. 

The only ones still hosted are the older legacy/1.6 ones on bukkitdev: https://dev.bukkit.org/projects/prism/files

Here's the repo bot prism for bukkit: https://github.com/prism/Prism-Bukkit - but I don't recall if we had the mcpc code here or if blood maintained that separately.

**Comment by vedisdragon** [comment]
I did find this Cauldron compat version: https://github.com/prism/Prism-Bukkit/releases/tag/v2.0.2-CAULDRON
Thank you very much for your help!

**Comment by vedisdragon** [comment]
Apologies for bothering again, but could I get some help compiling this version into a .jar? No worries if not.

**Comment by viveleroi** [comment]
That branch (and the tag you linked) are managed with maven so you can run a `mvn compile` I believe, although I suspect they point at outdated bukkit/cauldron artifacts so it might be hard to work around that.
