### ISSUE TITLE
Error When using Cyclic's Sack of Holding

### ISSUE THREAD

**Issue by sandtechnology** [prism/Prism#118]
Log:https://paste.ubuntu.com/p/HrJR2KyBYQ/
Minecraft Forge: 14.23.5.2811
SpongeForge: 1.12.2-2768-7.1.5
SpongeAPI: 7.1.0-366290f8
Cyclic version:[1.17.16](https://minecraft.curseforge.com/projects/cyclic/files/2668442/download)
Prism version:[3.0.0-beta2-73-g659e7b5](http://helion3.com:8080/job/Prism/lastSuccessfulBuild/artifact/build/libs/prism-3.0.0-beta2-73-g659e7b5.jar)
Prism config:https://paste.ubuntu.com/p/jy8kQqpW2V/

**Comment by LXGaming** [comment]
Fixed in SpongeForge-1.12.2-2768-7.1.6-RC3657
