### ISSUE TITLE
MongoDB Security authentication exception

### ISSUE THREAD

**Issue by NEXUS2345** [prism/Prism#123]
Attempting to set up MongoDB as we are having issues with orphaned connections on our MariaDB instance which we believe is due to Prism. Using MongoDB 3.6.3 and getting the following error. This occurred both when MongoDB was running locally and remotely, and both within a Docker container and outside docker. Some data has been censored to protect our servers.

https://gist.github.com/NEXUS2345/1d93d4292c8a6964435f38f90660d66b

Any help is appreciated.

**Comment by LXGaming** [comment]
Can you confirm the user actually exists by running the following in mongo console:
```
use <DATABASE_NAME>
db.getUsers()
```

**Comment by NEXUS2345** [comment]
I figured out the issue now. I didn't give the user the correct roles for accessing the databases.

Apologies about that.

**Comment by NEXUS2345** [comment]
We are still having this issue apparently. I redid our MongoDB, on the same machine as the servers. Authentication is not enabled and the prism config is set correctly but as soon as more than a single server connects all connections are killed with a code 18 authentication exception.

**Comment by NEXUS2345** [comment]
I have managed to solve this properly this time. I believe that Mongo for some reason isn't allowing more than one connection to the database when authentication isn't enabled or something. I ended up creating users in each database with different usernames and passwords and that solves the issue.
