### ISSUE TITLE
Blocks duplication on placement

### ISSUE THREAD

**Issue by krisjenner** [prism/Prism#132]
log https://gist.github.com/krisjenner/5b7c7ad98d0f2fecd82900a4d633b228

Some blocks place but also don't leave players inventory when this error is in console

**Comment by LXGaming** [comment]
What version of Prism and Sponge are you running?

Can you please provide your latest.log and debug.log

**Comment by krisjenner** [comment]
prism-3.0.0-beta2-75-g9b005fd-7-g95cd240-all
Sponge 7.1.6 RC3616

I tried to upload the logs to gist/hastebin but they're too big :(

**Comment by LXGaming** [comment]
If you can try zipping the logs then uploading them (You might be able to upload the zip via a GitHub comment)

The Sponge build you are running is known to have a dupe issue, This appears to be fixed in newer builds: https://github.com/SpongePowered/SpongeForge/issues/2703

**Comment by krisjenner** [comment]
Hey! I believe it was Sponge doing the duping in this instance. Although I have another instance where I am 100% sure Prism is causing the dupe as it only started happening when I installed Prism on a test server.

It only happens on skulls or player heads though [GIF](https://gyazo.com/8d4670cd2397262918d4e9f6c88360ea)

not any other tile entities as far as i can see

[debug.log](https://gist.github.com/krisjenner/4ced1555de1c585c4e8bd3a383944b6a)

Prism version: prism-3.0.0-beta2-75-g9b005fd-7-g95cd240-all

Ty for the great plugin hope this can get resolved soon :)

**Comment by LXGaming** [comment]
This is another Sponge issue as I can replicate this issue without Prism by starting the server with the JVM argument `-Dsponge.shouldFireAll=true`. Sponge doesn't fire events unless a plugin is listening to it hence why this issue showed up when you installed Prism.

Create an issue on https://github.com/SpongePowered/SpongeCommon

**Comment by LXGaming** [comment]
Fixed by Sponge
