### ISSUE TITLE
Blocks removed when placed

### ISSUE THREAD

**Issue by WiiTee** [prism/Prism#133]
Installed the mod yesterday, but as soon as I placed blocks they would immediately be removed from the World and inventory as well. Logging back in would refund the blocks placed in the inventory.
I tried giving myself all permissions, but it did nothing to solve the issue.

Would like to share logs, but there were no errors or anything else given in the console.

Forge-1.12.2-14.23.5-2768
SpongeForge 7.1.5
Prism-3.0.0-beta2-75-g9b005fd-8-g0c0e840

**Comment by LXGaming** [comment]
Did you test this at your world spawn? I could only reproduce by removing OP and having `spawn-protection` set in the `server.properties`.

**Comment by WiiTee** [comment]
I was roughly 14k blocks away from Spawn.
There are no OPs on the Server (using permission plugins).
I do think there is a spawn-protection though. I will test without it.

**Comment by WiiTee** [comment]
Right, so.. If Spawn-Protection is enabled (doesn't matter how far or if set to 0), then you cannot place blocks at all regardless of how far away from Spawn you actually are.
Which, might be a bit extreme :).

Other than that cheers! It fixed it and I can now be safe in the knowledge that griefers are the one that gets griefed by vasting time.
