### ISSUE TITLE
Changing config throws errors in console

### ISSUE THREAD

**Issue by WiiTee** [prism/Prism#134]
Changing the config throws errors in the console, then reverts the config to the original version.

Using:
SpongeForge 7.1.5
Forge-1.12.2-14.23.5-2768
Prism-3.0.0-beta2-75-g9b005fd-8-g0c0e840

[debug-3.log](https://github.com/prism/Prism/files/3161123/debug-3.log)
[2019-05-09-5.log](https://github.com/prism/Prism/files/3161124/2019-05-09-5.log)

**Comment by LXGaming** [comment]
Whats values are you changing? Can you provide the modified config?

**Comment by WiiTee** [comment]
Changed the file name to modified, obviously in the config folder it would still be named prism.conf
Trying to change database type, username etc all throws those errors.

[prism_modified.conf.zip](https://github.com/prism/Prism/files/3161161/prism_modified.conf.zip)

**Comment by LXGaming** [comment]
Try wrapping the values in quotes

`address=localhost:8080` -> `address="localhost:8080"`
`database=prism` -> `database="prism"`
`engine=mysql` -> `engine="mysql"`

**Comment by LXGaming** [comment]
The address needs to be surrounded with quotes if it contains symbols
