### ISSUE TITLE
"mininglaser" went through FTB claim and runs error on inspect

### ISSUE THREAD

**Issue by krisjenner** [prism/Prism#138]
The error on inspect: https://gist.github.com/krisjenner/ed10577b8da174e4cd445b9dd10c037f

I'm assuming mininglaser is from IC2 but why wont it allow me to rollback? I get

 `java.lang.Integer cannot be cast to java.lang.Byte`

when trying to rollback

this was on `prism-3.0.0-beta2-75-g9b005fd-12-g5435fdd`

**Comment by krisjenner** [comment]
managed to roll it back using `prism-3.0.0-beta2-75-g9b005fd-7-g95cd240-all.jar` but it doesn't save Refined Storage storage disks that are in disk drives and only gives back the empty disk drive

**Comment by LXGaming** [comment]
Try this build https://github.com/prism/Prism/releases/tag/issue-138

I've added a try-catch which will hopefully output the id and location of the block that's causing the error to console.

As for Refined Storage it look like it stores all of it's data separate to the TileEntity/BlockEntity (What ever Sponge is calling it now) which is why Prism isn't able to rollback the disks as they aren't actually store in the block at all. (Use `/blockdata ~ ~-1 ~ {}` while standing on the block to view the NBT data of it).

**Comment by krisjenner** [comment]
Thank you so much! It now outputs [this ](https://gist.github.com/krisjenner/651667f6c78b51517d586cc0e87ef17f)

Also, rolling back AE drives with the previous version caused the drives to show items in tooltip but not display them in AE system - but with this version they roll back with no issue. 

Thought i'd say

**Comment by krisjenner** [comment]
Got this crash on rolling back some damage done with mining laser [crash](https://gist.github.com/krisjenner/5d744007be5c26d107db082924a5f85f)

**Comment by clienthax** [comment]
```
[15:41:57] [Server thread/ERROR] [prism]: Failed to deserialize ironchest:iron chest at MemoryDataContainer{safety=ALL_DATA_CLONED, map={X=-10590, Y=76, Z=-22417, WorldUuid=7fead09c-df6b-432e-b4c0-ec00b44c988b}}
> [15:41:57] [Server thread/INFO] [STDERR]: [com.helion3.prism.commands.ApplierCommand:lambda$null$1:147]: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
```

**Comment by LXGaming** [comment]
@clienthax Can you provide a list of items that were in the chest? Or a list of mods on your server as I'm unable to reproduce that error with only the chest, Seems like something inside the chest is causing issues

**Comment by LXGaming** [comment]
This build should fix the issue: https://github.com/prism/Prism/releases/tag/prism-3.0.0-9de83e235d
