### ISSUE TITLE
Unsupported Json list data type

### ISSUE THREAD

**Issue by pinipy** [prism/Prism#148]
[pool-3-thread-52-ERROR] [prism]: Unsupported Json list data type: [I for key slaves. 

This is the error that I am getting. 
Only started seeing it when I installed DecoCraft. When I place a Deco craft block it spams console

**Comment by viveleroi** [comment]
Can you post a full error log? It looks like this is only part of the error message, but I know some web console truncate these.

**Comment by pinipy** [comment]
This is all I'm seeing in console

**Comment by LXGaming** [comment]
What version of Prism are you running?

**Comment by pinipy** [comment]
Running Prism 3.0.0 beta

**Comment by LXGaming** [comment]
Can you provided the file name of the Prism plugin jar?

**Comment by pinipy** [comment]
Prism-3.0.0-beta2-48-g39b8d2f-all

**Comment by LXGaming** [comment]
Please test with this version https://github.com/prism/Prism/releases/tag/f456812 as it's the latest.

I'm not sure if we have any Jenkins servers building Prism.

**Comment by pinipy** [comment]
Should I download the prism.jar or the prism-all.jar?

**Comment by viveleroi** [comment]
@LXGaming We don't have a jenkins/etc servers currently.

**Comment by LXGaming** [comment]
If you use MongoDB you need `-all` otherwise use the other one

**Comment by LXGaming** [comment]
@viveleroi Ah ok, What I'm hoping to do is when Ore moves its changes from staging to production I want to get Travis CI to upload builds directly to Ore. I've already built a [bash script](https://github.com/LXGaming/OreDeploy/blob/master/scripts/deploy) which does this.

**Comment by LXGaming** [comment]
Reopen if this is still an issue after updating.
