### ISSUE TITLE
Soft incompatibility with EliteMobs

### ISSUE THREAD

**Issue by B-Knight49** [prism/Prism#163]
Using EliteMobs alongside Prism throws the occasional error in console on EntityDeathEvent.

Error link: https://gist.github.com/B-Knight49/ce205f6bc00d7ef67a438defa65549e0

**Comment by viveleroi** [comment]
You're using Prism for bukkit API, which is maintained here: https://github.com/AddstarMC/Prism-Bukkit

**Comment by B-Knight49** [comment]
Oops, sorry, my bad!
