### ISSUE TITLE
org.mongodb.driver.connection]: Closed connection

### ISSUE THREAD

**Issue by Jpofin** [prism/Prism#173]
I am getting following error once I set the plugin to use mongodb:
https://pastebin.com/dtW0Mcif

Config:
`storage {
    # The address and port for the database
    # - Specify as 'host:port' if it differs from default
    address=localhost
    # The name of the database
    database=pixelmon_prism
    # The database engine
    #   (H2, MongoDB, MySQL)
    engine=MongoDB
    # The amount of time records are stored for
    expire-records="8w"
    # Maximum size of the MySQL connection pool
    maximum-pool-size=10
    # Minimum number of idle connections that the pool will try to maintain
    minimum-idle=2
    # Credential for the database
    password="PA$$W0RDH3R3!!?!"
    # Amount of records to purge at a time
    purge-batch-limit=100000
    # The prefix of all SQL tables.
    table-prefix="prism_"
    # Credential for the database
    username=pixelmon_prism
}`

Am I doing something wrong?

**Comment by viveleroi** [comment]
> Authentication failed

Wrong username or password, maybe you can't login from the server's address, etc. Something with authenticating.

However, this project is fairly out of date so I'm not sure how useful it'll be for you.
