### ISSUE TITLE
Rollback trees do not work correctly

### ISSUE THREAD

**Issue by bloodmc** [prism/Prism#19]
1. Grow a tree using sapling.
2. Blow up tree with TNT
3. Use command /pr rb r:10
Tree that is restored is missing a ton of blocks.

**Comment by viveleroi** [comment]
While this actually led me to the fact that SQL-based queries weren't being sorted right, the specific issue you mention is actually the expected result with the parameters you used.

In the exact series of steps, you'll have place records for the entire tree, but only break records for those blocks which blew up. When you do `/pr rb r:10` you're going to rollback every entry in that radius (in order of the timestamp).

What happens is you see ~50 breaks rollback (which puts the blocks back in the world), but you're also rolling back ~100 *place* events for blocks that never got destroyed.

The solution is to use an action like `/pr rb r:10 a:break`. That way the *place* events aren't reversed too.

Luckily outside of testing, this doesn't come up much. Prism 1/2 had a default time parameter of the past 3 days (which I need to add to v3) and in a real environment, things aren't usually griefed that quickly.
