### ISSUE TITLE
entity-spawn-animals being logged despite set to false

### ISSUE THREAD

**Issue by PhanaticD** [prism/Prism#2]
On the cauldron version of prism build 16 from here: http://dhmc.us:8080/job/Prism-Cauldron/16/

entity-spawn-animals is set to false for logging, however it is being logged anyway. This especially a major pain on pixelmon as thousands of this event can occur after just a few minutes filling up the database

**Comment by viveleroi** [comment]
This isn't the correct place to file issues - this repo is for Prism/Sponge work, and the issues tab shouldn't be open anyway.
