### ISSUE TITLE
The console has been repeating the information

### ISSUE THREAD

**Issue by bunSakurAing** [prism/Prism#30]
`
15.03 21:13:16 [服务器] 位置: org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1068) [CauseTracker.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:445) [CauseTracker.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:751) [CauseTracker.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:128) [SpongeImpl.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:251) [SpongeModEventManager.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:283) [SpongeModEventManager.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:239) [SpongeModEventManager.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1763-4.1.0-BETA-1208]
15.03 21:13:16 [服务器] 位置: org.spongepowered.common.event.listener.ChangeBlockEventListener_ChangeBlockListener_onChangeBlock92.handle(Unknown Source) ~[?:?]
15.03 21:13:16 [服务器] 位置: com.helion3.prism.events.listeners.ChangeBlockListener.onChangeBlock(ChangeBlockListener.java:72) ~[ChangeBlockListener.class:3.0.0-beta2+unknown-b0.git-unknown]
15.03 21:13:16 [服务器] 位置: com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.decayedBlock(PrismRecord.java:178) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2+unknown-b0.git-unknown]
15.03 21:13:16 [服务器] 位置: com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.writeBlockTransaction(PrismRecord.java:245) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2+unknown-b0.git-unknown]
15.03 21:13:16 [服务器] Server thread/严重错误 [Sponge]: Could not pass ChangeBlockEvent$Decay$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@113cedb6`
This makes my server delay is very high, I hope can solve

**Comment by viveleroi** [comment]
What version of Sponge are you using? Where did you get the build of Prism from?

**Comment by bunSakurAing** [comment]
Sponge 4.1.0-BETA-1208
download from:http://dhmc.us:8080/job/Prism/

**Comment by viveleroi** [comment]
It's because Sponge changed the format of some of the data, I knew that was coming but didn't realized it had already landed in master. I'll get started on changes.

**Comment by ProsperCraft** [comment]
I am having the same issue with spongeforge-1.8.9-1763-4.1.0-BETA-1212.jar

http://pastebin.com/e5pLf1mf
