### ISSUE TITLE
Console message - NaN is not a valid double value as per JSON specification.

### ISSUE THREAD

**Issue by ProsperCraft** [prism/Prism#31]
http://pastebin.com/41eY6VTR

After updating to the latest version on Sponge 1212 I get this in console and it repeats.

**Comment by viveleroi** [comment]
What does you config file look like? I do not see the same issue.

**Comment by ProsperCraft** [comment]
http://pastebin.com/c0bEvmk8

**Comment by ProsperCraft** [comment]
Asking about the files got me thinking, the database and config were made with the old non working version, I wiped them and the errors quit.
