### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by KumaGetsu** [prism/Prism#36]
spongeforge-1.8.9-1808-4.1.0-BETA-1286

Console error:
http://paste.ubuntu.com/16055014/

**Comment by viveleroi** [comment]
Any steps to reproduce?

**Comment by KumaGetsu** [comment]
Just using the /prism i and left clicking an area which had block changes.

**Comment by KumaGetsu** [comment]
Even using the latest DevBuild this issue still persists.

**Comment by cartman-2000** [comment]
I get the same issue, the tool is useless at the current moment in time. Normal scanning still works.

Running with:
Minecraft: 1.10.2
SpongeAPI: 5.0.0-SNAPSHOT-05d0adc
SpongeForge: 1.10.2-2002-5.0.0-BETA-1533
Minecraft Forge: 12.18.0.2005

On windows 10.

And mysql 5.5.40 windows.

**Comment by cartman-2000** [comment]
You can try to download and build my branch of the plugin, I've gotten it to work on my own server.
https://github.com/prism/Prism/pull/39

**Comment by viveleroi** [comment]
Closing this, it's likely been solved by recent PRs. If not, we'll need more steps to reproduce.
