### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by SnowBlitzz** [prism/Prism#37]
http://pastebin.com/ySSzcEZ3

**Comment by viveleroi** [comment]
This isn't the whole error, and unfortunately it doesn't contain the important bits. Closing until I have the rest.

**Comment by SnowBlitzz** [comment]
I don't know what the whole error is since it's kinda the same message spamming the console over and over again. Is there a docu for the proper way to set up mysql in the config? I've been doing the same for other plugins but it doesn't work with prism.

**Comment by SnowBlitzz** [comment]
http://pastebin.com/Cwm0pkn8

Here it is. It only starts spamming the console with those when I broke a block. Just 1 single block.
