### ISSUE TITLE
Record purging

### ISSUE THREAD

**Issue by viveleroi** [prism/Prism#4]
It needs:
- Remove expired records (based on params would be best)
- Wipe database
- Batching, other ways to avoid db locks

**Comment by bloodmc** [comment]
This would be a good addition =)

**Comment by hunter688** [comment]
Please add to mysql adapter, now is only in the mongodb adapter.

**Comment by Yorkforce** [comment]
Any update to this?
MySQL database purge would be great if possible else it's going to create very large databases on busy servers.

**Comment by viveleroi** [comment]
I started work on it but have not had a chance to finish, yet.

**Comment by hunter688** [comment]
Im using this bash script for now:
<pre>
#!/bin/bash

timestamp=$(date +%s -d "14 day ago")
mysql --silent -u user -D databasename -e "delete from prism_records where Created<$timestamp"
idcko=$(mysql --silent -u user -D databasename -se "select id from prism_records order by id asc limit 1")
mysql --silent -u user -D databasename -e "delete from prism_extra where record_id<$idcko"
mysql --silent -u user -D databasename -e "optimize table prism_records"
mysql --silent -u user -D databasename -e "optimize table prism_extra"

</pre>

**Comment by phit** [comment]
for mongodb it's something like this

```
use yourdatabase
db.records.remove({Created: {$lte: new Date(2017, 3, 16)}});
```

replace date with whenever your newest entry should be that you want to keep, this is not really optimal though since it doesnt shrink the database size

**Comment by viveleroi** [comment]
Prism makes use of Mongo's native record expiration so the purging feature is really only needed for other DBs.

**Comment by phit** [comment]
oh, so it already works and uses the params set in the config for expiration?

**Comment by viveleroi** [comment]
For Mongo, yes. Records are saved with an `Expires` field which is a timestamp based on your config value.

**Comment by pietelite** [comment]
Can this be closed?

**Comment by viveleroi** [comment]
No, I don't believe record purging was ever added for non-mongo DBs

**Comment by phit** [comment]
was added in https://github.com/prism/Prism/pull/114

**Comment by viveleroi** [comment]
Ah, ok.
