### ISSUE TITLE
WEB UI not working with the SQL.

### ISSUE THREAD

**Issue by AnimadorX** [prism/Prism#45]
Prism already created the tables, but when I do a search on the WEB UI, the following error appears:
```
Error returning results:

The Ajax request failed.

Make sure WEB_UI_DEBUG is turned off in the config.php file. Otherwise, if you're unsure how to resolve this error please contact Prism support.

HTTP Status: 200 OK

Response Text: SELECT id, epoch, action, player, world, x, y, z, block_id, block_subid, old_block_id, old_block_subid, data FROM prism_data d INNER JOIN prism_players p ON p.player_id = d.player_id INNER JOIN prism_actions a ON a.action_id = d.action_id INNER JOIN prism_worlds w ON w.world_id = d.world_id LEFT JOIN prism_data_extra ex ON ex.data_id = d.id WHERE a.action NOT LIKE "%prism%" LIMIT 0,25;
```

**Comment by Eufranio** [comment]
I have same issue, thought was my error in something in the configs, i tried everything and still not working...

**Comment by viveleroi** [comment]
The web UI is not supported for Prism for Sponge. You can file an issue with https://github.com/prism/Prism-Bukkit but that project is no longer supported.

**Comment by Eufranio** [comment]
Well, so no one can answer our askings? Even if is not about requests...

**Comment by viveleroi** [comment]
I did answer. The web UI is not designed to work with Prism for Sponge which is where you're filing this issue. If you're using it for bukkit/spigot, it's not supported anymore. I will say that the issue you filed would be closed anyway because you have `WEB_UI_DEBUG` enabled which it specifically says to disable. If you disable it and still have errors then you need to run the sql manually and look at what MySQL complains about.

**Comment by Eufranio** [comment]
Prism-Bukkit doesn't have issues allowed, anyway one or another will come here asking about it, bcs we dont have another place to ask things... So, prism-bukkit devs dont want even simple askings? oh god.

**Comment by viveleroi** [comment]
It's not supported anymore, so issues filed against it are worthless. Filing a ticket is not the appropriate place to ask for help. Considering you're not answering my most basic questions I'm going to mute this thread.

**Comment by AnimadorX** [comment]
Same thing without the debug option.

**Comment by viveleroi** [comment]
If you expect help, you have to stop wasting my time. Two days ago I said:

> If you disable it and still have errors then you need to run the sql manually and look at what MySQL complains about.
