### ISSUE TITLE
[Sponge-5.0.0] Could not pass ChangeBlockEvent$Place

### ISSUE THREAD

**Issue by FiveEYZ** [prism/Prism#49]
Console error:
https://gist.github.com/FiveEYZ/9a17d929a1f297436c1985cfb889146b

using:
forge-1.10.2-12.18.1.2065-universal
spongeforge-1.10.2-2052-5.0.0-BETA-1675
Prism-3.0.0-beta2-11-gd3279c1-all

**Comment by Haidyn** [comment]
We don't have any console errors however, with `place=true` it doesn't seem to log block placements, other logs seem fine.

```
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-d41be56
    SpongeForge: 1.10.2-2052-5.0.0-BETA-1668
    Minecraft Forge: 12.18.1.2057
    Prism-3.0.0-beta2-11-gd3279c1-all
```

**Comment by FiveEYZ** [comment]
don't really know what happen, but all of a sudden it started to spam and then it stopped:
https://gist.github.com/FiveEYZ/4bf226c1dedec7823e4f0a91c6155d6d

**Comment by ProsperCraft** [comment]
Same console error-
http://pastebin.com/Rm5jVptZ

**Comment by LemADEC** [comment]
This issues appeared on our server while testing liquids, logs of them on each others:
![image](https://cloud.githubusercontent.com/assets/4776032/19022913/d420fa62-88e2-11e6-9717-048c4d431318.png)

**Comment by viveleroi** [comment]
The error is from Sponge itself and wouldn't be something Prism can fix. It indicates that some value was null from a block snapshot. I don't the see the issue with vanilla liquids so either it's mod-related or has been fixed.
