### ISSUE TITLE
[Suggestion] Show co-ordinates or allow teleporting to records from /pr lookup

### ISSUE THREAD

**Issue by Haidyn** [prism/Prism#50]
Unless you're next to the area you're wanting to lookup, the /pr l command is no longer useful in any other respect as there's no way to find or go to the area of the records you find.

It seems as though the information provided when you're inspecting a block is what should be shown on lookup.

/pr lookup result:
![Lookup](http://i.nentify.me/8qD5cRtF.png)

/pr inspect result
![Inspect](http://i.nentify.me/Sb8jayY6.png)

**Comment by viveleroi** [comment]
You can always teleport via click to extended/no-group results, but you're showing a grouped lookup which cannot return coordinates because it's grouped.

**Comment by Haidyn** [comment]
Is there a way to return ungrouped results from a lookup in this version?

The 1.7 version returned grouped results with ID's which you could then /pr tp to which was invaluable to do larger scale searches for specific things. Lookup now returns results with no use.

**Comment by viveleroi** [comment]
Use the `--no-group` flag, or even `--extended`. So `/pr l p:viveleroi --no-group` Ideally, specific data like IDs should *never* be displayed when records are grouped and the only reason Prism 1/2 did that was because older versions of MySQL tolerated it.

**Comment by Nentify** [comment]
Seems you need to put only 1 dash before the flag.

**Comment by viveleroi** [comment]
Oh good catch, guess I need to update the readme.
