### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by DeJayDevelopment** [prism/Prism#51]
Hi there. I've been having an issue with Prism and MySQL. The database information is all proper but I am constantly being told something along the lines of:
Cannot add or update a child row: a foreign key constraint fails (`apexMC28027`.`prism_data_extra`, CONSTRAINT `prism_data_extra_ibfk_1` FOREIGN KEY (`data_id`) REFERENCES `prism_data` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)

apexMC28027 being my login username.
Databases created by other plugins present no current issue:
https://gyazo.com/a65091a23d0ffdb492047535f876f897

**Comment by viveleroi** [comment]
This error is for Prism for Bukkit which isn't supported anymore. https://github.com/prism/Prism-Bukkit

The error means Prism was unable to correctly save data and relational data is missing.
