### ISSUE TITLE
Console Server Error

### ISSUE THREAD

**Issue by yepidoodles** [prism/Prism#71]
Not really an issue, just an error that keeps appearing in my console.

`[Thread-17/ERROR] [prism/sponge]: Unsupported json list data type: [I for key slaves`

I don't know what it is or why it keeps appearing.

- Alice
[DragonTechMC](http://dragontechmc.com)

**Comment by viveleroi** [comment]
Even with the full error I probably couldn't identify the issue without digging into the mod causing the issue. The error means some mod is storing block meta data with a type Prism is accounting for in its serialization.
