### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by yepidoodles** [prism/Prism#73]
This crash generated 2 reports (In 3 years of running servers, I've never seen that)

**First**
crash-2017-02-22_23.55.45-server
http://www.codesend.com/view/3b45db9ae75eb0360e64e973fd04ad3c/

**Second**
crash-2017-02-22_23.55.48-server
http://www.codesend.com/view/224937a0d5ff1db76a5038516e95c11d/

I believe it was caused when a player was fighting the Chaos Dragon from Draconic Evolution, and a Chaos Island Exploded (I've never seen this, or know how it works, it's just what he told me.).

I don't expect anything from this, I just thought you should know.

- Alice
[DragonTechMC](http://dragontechmc.com)

**Comment by viveleroi** [comment]
Neither of these are caused by Prism, they should be reported to the spongeforge project.
