### ISSUE TITLE
Invalid BSON field name tconstruct.spawned_book

### ISSUE THREAD

**Issue by KasperFranz** [prism/Prism#90]
We are getting this error from time to time on console: https://gist.github.com/KasperFranz/519b8dd2db4bdd3cb0cd61936efb53d7

it is a custom build where the only change is that it is uild for the API 5.2 instad of 6.0

**Comment by viveleroi** [comment]
We'll have to encode the period, that's what's causing this error. I'll have to look into possible solutions.

**Comment by Sir-Will** [comment]
Same issue here, spams the log every few minutes. Any news to this?

**Comment by phit** [comment]
sadly this is still [relevant](https://gist.github.com/phit/99f0318fd28fcbb46492a220fad3a554), weird that the mongo driver wouldnt handle this

https://jira.mongodb.org/browse/SERVER-30575

**Comment by LXGaming** [comment]
@phit This build should fix this issue as well as several others involving MongoDB: https://github.com/prism/Prism/releases/tag/3.0.0-beta2-75-g9b005fd-12-g5435fdd
