### ISSUE TITLE
Problems with events (mobs dying and other)

### ISSUE THREAD

**Issue by BrainStone** [prism/Prism#92]
Occationally I get these stacktraces in the console:
https://pastebin.com/PBJcAdwq
https://pastebin.com/4nELVTe9

SpongeForge: 1.11.2-2282-6.0.0-BETA-2287
Prism: 3.0.0-beta2-44-g18fa2a4-all

**Comment by viveleroi** [comment]
Do you have any idea what caused these? They show up during a block change event and it's likely a change in Sponge that Prism needs to adjust to so I'm speaking with them, but I also need to figure out how to reproduce it.

**Comment by viveleroi** [comment]
Actually, because this happens simply when we call their `toContainer` API method, I don't believe this is something we can fix because the error occurs in Sponge entirely. I'll still work with them on finding a solution but will close since it's not something caused by Prism.

**Comment by BrainStone** [comment]
I know what are causing these:
https://pastebin.com/PBJcAdwq: When a container like a double chest gets placed or broken
https://pastebin.com/4nELVTe9: When an entity dies.

**Comment by viveleroi** [comment]
gabizou says he'll have a fix in for this soon, it is an issue on the sponge side.
