### ISSUE TITLE
Console Spamming error

### ISSUE THREAD

**Issue by pocketpixelsmc** [prism/Prism#94]
The console is spamming the following error:

https://hastebin.com/emijobiwuq.css

**Comment by viveleroi** [comment]
This error isn't enough to go on, the `db` is null meaning it failed outside of Prism's control. If you see any other H2-related errors, that will help you determine the issue.

**Comment by pocketpixelsmc** [comment]
I can't seem to figure out the issue.

https://gyazo.com/53a5fd0aa2ba9e14bcfb1a921133a666
These are the 3 files and there don't seem to be any issues with them. Would you be able to help?
