### ISSUE TITLE
Error on Entity Death

### ISSUE THREAD

**Issue by t2wave** [prism/Prism#97]
Running: 
forge-1.11.2-13.20.0.2282-universal
spongeforge-1.11.2-2282-7.0.0-BETA-2327
Prism-3.0.0-beta2-45-gfbbeb2b-all
LuckPerms-Sponge-3.0.68
griefprevention-1.11.2-3.1.1.289
Nucleus-0.27.1-1.11.2-S6.0-plugin

https://pastebin.com/kt5FhVhm

**Comment by viveleroi** [comment]
This is a Sponge issue which gabizou has committed to fix, duplicate of #92
