### ISSUE TITLE
Command error/Console spam

### ISSUE THREAD

**Issue by spectrumization** [prism/Prism#98]
Whenever I try to inspect a block or look at changes near me it says Error please see console so i got to console and theres nothing really there its just spamming it a lot here the log from when i logged in /pr i and hit a block until the end of it https://pastebin.com/zjMhSWiRhttps://pastebin.com/zjMhSWiR

**Comment by viveleroi** [comment]
The error points to the database connecting no longer being valid. There must be errors occurring before this, because in order for it to be null, the database connection must have failed.
