### ISSUE TITLE
"Unsupported json list data type" console spam

### ISSUE THREAD

**Issue by capybara512** [prism/Prism#99]
Recently, I logged into my server's console to be greeted with the following console spam:
![screenshot from 2017-05-29 17-38-40](https://cloud.githubusercontent.com/assets/24247038/26563298/b3d8a2c2-4495-11e7-8bf3-19d4f95b325a.png)
(I can't get a copy/paste of it because there is too much spam being printed, which undoes my selection)

There are no recent changes that I can think of that may have caused this, although I did recently add an AutoBroadcaster plugin. As far as I can see, it just randomly started.

Versions:
SpongeForge: 1.10.2-2254-5.2.0-BETA-2272
Forge: 1.10.2-12.18.3.2254-universal
Prism: 3.0.0-beta2-44-g18fa2a4-all
FTB Beyond Modpack: 1.7.0

**Comment by viveleroi** [comment]
It's most likely something specific to a single block or type of blocks, maybe it began when those blocks were first used. I'll see if I can figure out what kind of data those keys are storing. Any idea which mod/block is causing this?

Which mods deal with redstone and might have the initials "OC"?

**Comment by capybara512** [comment]
OpenComputers probably does something redstone related. @viveleroi

**Comment by axle2005** [comment]
Update Spongeforge... thats a very old version.

**Comment by capybara512** [comment]
Updating SpongeForge to 5.2.0 has no effect.

**Comment by pinipy** [comment]
Hello I'm getting this error as well but mine says [I for key slaves 
At the end
